version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "example-package"  # Add any dependencies you want to ignore
    commit-message:
      prefix: "deps"
      include: "scope"
    target-branch: "main"  # Adjust as necessary
    open-pull-requests-limit: 5